name: bovino
description: "Aplicación para reconocimiento de ganado bovino usando cámara en vivo y TensorFlow"
publish_to: 'none'

version: 1.1.2

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Cámara y permisos
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  
  # HTTP requests para APIs
  dio: ^5.4.0

  # Manejo de imágenes
  path_provider: ^2.1.2
  
  # UI y utilidades
  flutter_spinkit: ^5.2.0
  
  # Clean Architecture
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  injectable: ^2.3.2
  
  # Estado y navegación
  flutter_bloc: ^8.1.4
  go_router: ^14.2.7
  
  logger: ^2.0.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Generación de código (solo lo esencial)
  build_runner: ^2.4.12
  injectable_generator: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

# Configuración para compilación rápida
flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
  
  # Comentamos las fuentes personalizadas por ahora para compilación más rápida
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300 