name: bovino
description: "Aplicación para reconocimiento de ganado bovino usando IA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Cámara y permisos
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  
  # HTTP requests para APIs
  http: ^1.2.0
  dio: ^5.4.0
  
  # Manejo de imágenes
  image: ^4.1.7
  path_provider: ^2.1.2
  
  # UI y utilidades
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.7
  
  # Clean Architecture
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  injectable: ^2.3.2
  
  # Estado y navegación
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  
  # Base de datos local
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  
  # Utilidades
  uuid: ^4.4.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Generación de código
  build_runner: ^2.4.12
  injectable_generator: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true 